// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolyConecta.Infrastructure.Persistence;

#nullable disable

namespace PolyConecta.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PolyDbContext))]
    [Migration("20261005234548_F0_Base")]
    partial class F0_Base
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolyConecta.Domain.Entities.Bom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LayerAPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LayerBPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LayerCPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Boms", "prd");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.BomLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ComponentPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BomId");

                    b.HasIndex("ProductId");

                    b.ToTable("BomLines", "prd");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.LotGenealogy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChildLotNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentLotNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("QuantityConsumedKg")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.Property<Guid?>("SourceRollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TargetRollId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("poly_lot_genealogy", "inv");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.ManufacturingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ContpaqDocumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CreditApproved")
                        .HasColumnType("bit");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProcessType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ProductQtyProduced")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProductQtyTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SalesApproved")
                        .HasColumnType("bit");

                    b.Property<decimal>("ScrapQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkCenterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ManufacturingOrders", "prd");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.MassBalanceAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AuditPassed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AuditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlagReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TotalMpInputKg")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<decimal>("TotalRollOutputKg")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<decimal>("TotalScrapOutputKg")
                        .HasPrecision(12, 3)
                        .HasColumnType("decimal(12,3)");

                    b.Property<decimal>("VariancePercentage")
                        .HasPrecision(6, 3)
                        .HasColumnType("decimal(6,3)");

                    b.HasKey("Id");

                    b.ToTable("poly_mass_balance_audits", "prd");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.PolyLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CidAlmacenContpaq")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlantCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("WarehouseType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CidAlmacenContpaq")
                        .IsUnique();

                    b.HasIndex("LocationCode")
                        .IsUnique();

                    b.ToTable("poly_locations", "inv");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CidAlmacenContpaq = 1,
                            IsActive = true,
                            LocationCode = "PIM/Stock/MP",
                            LocationName = "Apodaca MP Stock",
                            PlantCode = "PIM",
                            WarehouseType = "RawMaterial"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CidAlmacenContpaq = 2,
                            IsActive = true,
                            LocationCode = "PIM/Produccion",
                            LocationName = "Apodaca WIP Production",
                            PlantCode = "PIM",
                            WarehouseType = "Production"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CidAlmacenContpaq = 3,
                            IsActive = true,
                            LocationCode = "PIM/Stock/PT",
                            LocationName = "Apodaca PT Stock",
                            PlantCode = "PIM",
                            WarehouseType = "FinishedGoods"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CidAlmacenContpaq = 4,
                            IsActive = true,
                            LocationCode = "PIM/Cuarentena",
                            LocationName = "Apodaca Quality Quarantine",
                            PlantCode = "PIM",
                            WarehouseType = "Quarantine"
                        });
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContpaqProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products", "inv");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.QualityCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DynesMeasured")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GaugeMeasured")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("InspectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ManufacturingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QualityState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StockLotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("VisualInspectionPassed")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingOrderId");

                    b.HasIndex("StockLotId");

                    b.ToTable("QualityChecks", "cal");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.RawMaterialCatalog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("CidProductoContpaq")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DensityGcm3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InternalSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MfiMeltFlowIndex")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TargetHopper")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("InternalSku")
                        .IsUnique();

                    b.ToTable("poly_raw_material_catalogs", "inv");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "VirginResin",
                            CidProductoContpaq = 101,
                            CreatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DensityGcm3 = 0.958m,
                            InternalSku = "MP-RES-HD-001",
                            IsActive = true,
                            MfiMeltFlowIndex = 0.95m,
                            Name = "Resina PE Alta Densidad Alathon M6210",
                            TargetHopper = "Tolva A"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "VirginResin",
                            CidProductoContpaq = 102,
                            CreatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DensityGcm3 = 0.922m,
                            InternalSku = "MP-RES-LD-002",
                            IsActive = true,
                            MfiMeltFlowIndex = 2.00m,
                            Name = "Resina PE Baja Densidad Braskem BC818",
                            TargetHopper = "Tolva B"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Category = "Additive",
                            CidProductoContpaq = 103,
                            CreatedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DensityGcm3 = 0.940m,
                            InternalSku = "MP-ADI-UV-001",
                            IsActive = true,
                            MfiMeltFlowIndex = 1.10m,
                            Name = "Masterbatch Aditivo Anti-UV Clariant",
                            TargetHopper = "Tolva C"
                        });
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.StockLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ContpaqWarehouseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StockLocations", "inv");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.StockLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContpaqLotNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentLocationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DynesCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GaugeMicron")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LengthMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ManufacturingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProducedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TareWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WidthMm")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockLots", "inv");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.StockMove", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DestinationLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationDestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ManufacturingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ProductUomQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("SourceLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StockLotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StockPickingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SourceLocationId");

                    b.HasIndex("StockLotId");

                    b.HasIndex("StockPickingId");

                    b.ToTable("StockMoves", "inv");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.StockPicking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DestinationLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationDestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PickingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SourceLocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLocationId");

                    b.HasIndex("SourceLocationId");

                    b.ToTable("StockPickings", "inv");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.StockScrap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ManufacturingOrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ScrapQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScrapReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturingOrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("StockScraps", "prd");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.SupplierProductMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MappedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RawMaterialCatalogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SupplierProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("RawMaterialCatalogId");

                    b.ToTable("poly_supplier_product_mappings", "inv");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            MappedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            RawMaterialCatalogId = new Guid("55555555-5555-5555-5555-555555555555"),
                            SupplierCode = "LYONDELL",
                            SupplierProductName = "Alathon M6210 High Density Polyethylene",
                            SupplierSku = "LYO-M6210-HD"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            MappedAt = new DateTime(2026, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            RawMaterialCatalogId = new Guid("66666666-6666-6666-6666-666666666666"),
                            SupplierCode = "BRASKEM",
                            SupplierProductName = "Braskem BC818 Low Density Polyethylene",
                            SupplierSku = "BRASK-BC818"
                        });
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.Bom", b =>
                {
                    b.HasOne("PolyConecta.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.BomLine", b =>
                {
                    b.HasOne("PolyConecta.Domain.Entities.Bom", null)
                        .WithMany("Lines")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyConecta.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.ManufacturingOrder", b =>
                {
                    b.HasOne("PolyConecta.Domain.Entities.ManufacturingOrder", "ParentOrder")
                        .WithMany("ChildOrders")
                        .HasForeignKey("ParentOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolyConecta.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.QualityCheck", b =>
                {
                    b.HasOne("PolyConecta.Domain.Entities.ManufacturingOrder", "ManufacturingOrder")
                        .WithMany()
                        .HasForeignKey("ManufacturingOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolyConecta.Domain.Entities.StockLot", "StockLot")
                        .WithMany()
                        .HasForeignKey("StockLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ManufacturingOrder");

                    b.Navigation("StockLot");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.StockLot", b =>
                {
                    b.HasOne("PolyConecta.Domain.Entities.ManufacturingOrder", "ManufacturingOrder")
                        .WithMany()
                        .HasForeignKey("ManufacturingOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolyConecta.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManufacturingOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.StockMove", b =>
                {
                    b.HasOne("PolyConecta.Domain.Entities.StockLocation", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolyConecta.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyConecta.Domain.Entities.StockLocation", "SourceLocation")
                        .WithMany()
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolyConecta.Domain.Entities.StockLot", "StockLot")
                        .WithMany()
                        .HasForeignKey("StockLotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolyConecta.Domain.Entities.StockPicking", null)
                        .WithMany("Moves")
                        .HasForeignKey("StockPickingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DestinationLocation");

                    b.Navigation("Product");

                    b.Navigation("SourceLocation");

                    b.Navigation("StockLot");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.StockPicking", b =>
                {
                    b.HasOne("PolyConecta.Domain.Entities.StockLocation", "DestinationLocation")
                        .WithMany()
                        .HasForeignKey("DestinationLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolyConecta.Domain.Entities.StockLocation", "SourceLocation")
                        .WithMany()
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DestinationLocation");

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.StockScrap", b =>
                {
                    b.HasOne("PolyConecta.Domain.Entities.ManufacturingOrder", "ManufacturingOrder")
                        .WithMany()
                        .HasForeignKey("ManufacturingOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PolyConecta.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManufacturingOrder");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.SupplierProductMapping", b =>
                {
                    b.HasOne("PolyConecta.Domain.Entities.RawMaterialCatalog", "RawMaterialCatalog")
                        .WithMany("SupplierMappings")
                        .HasForeignKey("RawMaterialCatalogId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RawMaterialCatalog");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.Bom", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.ManufacturingOrder", b =>
                {
                    b.Navigation("ChildOrders");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.RawMaterialCatalog", b =>
                {
                    b.Navigation("SupplierMappings");
                });

            modelBuilder.Entity("PolyConecta.Domain.Entities.StockPicking", b =>
                {
                    b.Navigation("Moves");
                });
#pragma warning restore 612, 618
        }
    }
}
