import { guion } from './runner';

const MODAL = 'div.position-fixed';

/** US-2, escenario 4: traslado, recepción y entrega, con estados y Contpaq ID en cada paso. */
guion({
  nombre: 'traslado, recepción y entrega',
  pasos: [
    { ir: '/traslados/PIM/OUT/48213' },
    { control: 'traslado inicial', en: 'main' },
    { pulsar: '.o_statusbar button', texto: 'Comprobar disponibilidad' },
    { pulsar: '.o_statusbar button', texto: 'Validar' },
    { control: 'traslado paso 1', en: 'main' },
    { pulsar: '.o_statusbar button', texto: 'Validar' },
    { pulsar: '.o_statusbar button', texto: 'Validar' },
    { control: 'traslado listo', en: 'main' },
    { pulsar: '.o_statusbar button', texto: 'Validar' },
    { control: 'traslado sin lotes', en: 'main' },
    { pulsar: 'main td button.btn-link' },
    { elegirLote: `${MODAL} input[placeholder^=Escanear]`, lote: 'R001-IV310-26' },
    { elegirLote: `${MODAL} input[placeholder^=Escanear]`, lote: 'NO-EXISTE' },
    { control: 'modal traslado', en: MODAL },
    { pulsar: `${MODAL} button`, texto: 'Cerrar' },
    { pulsar: '.o_statusbar button', texto: 'Validar' },
    { control: 'traslado hecho', en: 'main' },
    { pulsar: '.o_smart_button', texto: 'Recepción' },
    { control: 'recepción', en: 'main' },
    { pulsar: '.o_statusbar button', texto: 'Validar' },
    { pulsar: '.o_statusbar button', texto: 'Validar' },
    { pulsar: 'main td button.btn-link' },
    { elegirLote: `${MODAL} input[placeholder^=Escanear]`, lote: 'R001-IV310-26' },
    { elegirLote: `${MODAL} input[placeholder^=Escanear]`, lote: 'R002-IV310-26' },
    { elegirLote: `${MODAL} input[placeholder^=Escanear]`, lote: 'R003-IV310-26' },
    { pulsar: `${MODAL} button`, texto: 'Cerrar' },
    { pulsar: '.o_statusbar button', texto: 'Validar' },
    { control: 'recepción hecha', en: 'main' },
    { navegar: '/entregas/SC/OUT/31688' },
    { control: 'entrega', en: 'main' },
    { pulsar: '.o_statusbar button', texto: 'Validar' },
    { pulsar: '.o_statusbar button', texto: 'Validar' },
    { pulsar: 'main td button.btn-link' },
    { control: 'modal entrega', en: MODAL },
    { pulsar: `${MODAL} button`, texto: 'Cerrar' },
    { pulsar: '.o_statusbar button', texto: 'Validar' },
    { control: 'entrega sin lotes', en: 'main' },
    { navegar: '/pedidos/IV310-26' },
    { control: 'pedido tras logística', en: 'main' },
    { navegar: '/inventario' },
    { control: 'inventario tras logística', en: 'main' },
  ],
});
